<template>
<div id = "projects">
  <div class = "homepage-project" v-for = "project in projects" :key = "project.id" v-bind:style = "{ backgroundImage: 'url(' + project.cover + ')' }">
    <div class = "text-container">
      <h1>{{project.title}}</h1>
      <BaseTag v-for = "tag in project.tags" :key = "tag.id" :text = "tag.text" /><br />
      <pre>{{project.description}}</pre>
      <BaseButton :url = "project.studyUrl" text = "Case Study" />
      <BaseButton :url = "project.url" text = "Check it out" />
    </div>
  </div>
</div>
</template>

<script>
import BaseButton from './BaseButton'
import BaseTag from './BaseTag'
export default {
  name: 'TheProjectsSection',
  components: {BaseButton, BaseTag},
  data () {
    return {
      projects: [
        {
          id: 0,
          title: 'University of Bristol',
          description: `Built application for clients, students, and lecturers to interact with their
respective projects from the Software Product Engineering unit.`,
          tags: [
            {
              id: 1,
              text: 'JS'
            },
            {
              id: 2,
              text: 'Vue.js'
            },
            {
              id: 3,
              text: 'Java'
            },
            {
              id: 4,
              text: 'UX'
            }
          ],
          cover: require('../assets/project-covers/uob-cover.jpg'),
          url: ' ',
          studyUrl: '/project/bristolSPE'
        },
        {
          id: 1,
          title: 'Alces',
          tags: [
            {
              id: 1,
              text: 'JS'
            },
            {
              id: 2,
              text: 'UX'
            },
            {
              id: 3,
              text: 'Big Data'
            }
          ],
          description: `Built web dashboard to run statistical tests against ALCES data.
Complex data sets generated by monitoring programs can now be
summarized, visualized, and analyzed with ease.`,
          cover: require('../assets/project-covers/alces-cover.jpg'),
          url: ' ',
          studyUrl: '/project/alces'
        },
        {
          id: 2,
          title: 'East European Comic-Con',
          description: `Was in charge of coordinating the team that handled local and online
marketing, design, development, and live online broadcasting.`,
          tags: [
            {
              id: 1,
              text: 'Print'
            },
            {
              id: 2,
              text: 'Marketing'
            }
          ],
          cover: require('../assets/project-covers/eecc-cover.jpg'),
          url: 'http://www.eecc.com',
          studyUrl: '/project/eecc'
        },
        {
          id: 3,
          title: 'Esportsify',
          tags: [
            {
              id: 1,
              text: 'JS'
            },
            {
              id: 2,
              text: 'PHP'
            },
            {
              id: 3,
              text: 'UX'
            }
          ],
          description: `Developed various Web Applications in the eSports industry.
Most of my work contributed to Ryze, a streaming platform that
aimed to provide the complete experience for eSports fans.`,
          cover: require('../assets/project-covers/esportsify-cover.jpg'),
          url: 'http://www.esportsify.com',
          studyUrl: '/project/esportsify'
        }
      ]
    }
  }
}
</script>

<style scoped>
  .homepage-project{
    background-size: cover;
    height: 420px;
    position: relative;
  }
  .homepage-project h1,pre{
    text-align: left;
    color: #fefefe;
    margin: 0px;
    padding: 0px;
  }
  .homepage-project h1{
    font-size: 2em;
    font-weight: 400;
    text-shadow : 0 3px 4px rgba(0,0,0,0.40);
  }
  .homepage-project pre{
    font-family: "Work Sans", sans-serif;
    font-weight: 300;
    font-size: 1.1em;
    margin-top: 1.2em;
  }
  .homepage-project .text-container{
    position: absolute;
    top: 50%;
    text-align: center;
    margin-left: 8%;
    -ms-transform: translate(0, -50%);
    -webkit-transform: translate(0, -50%);
    transform: translate(0, -50%);
  }
  .text-container a{
    float: left;
  }
</style>
